### ISSUE TITLE
Mouse Jittery is Fixed, but a camera issue shows up

### ISSUE THREAD

**Issue by gabl2312** [ermaccer/Worms4UHD.MouseFix#1]
Greetings.
First I would like to thank you for creating this fix, the random mouse jittery issue has been in the game for a long time without an apparent solution.
The fix works just as intended, however there seems to be a new issue that can arise after having the fix installed, the first person and third camera can't spin 360 degrees anymore.

I left a video example recorded by an friend for you to analyze below:

https://user-images.githubusercontent.com/88664090/128707595-ab0f9d4d-d57b-476a-a353-40a24637737a.mp4

Kind regards.

**Comment by GorgeousPuree** [comment]
same

**Comment by ermaccer** [comment]
Looks like the game uses DirectInput to get mouse position offscreen then keeps setting some cached value to match user desktop, I've disabled this function so therefore if mouse hits screen border - it will freeze.
I'll have to look around this.

**Comment by h3oCharles** [comment]
can confirm, if it helps, the problem also appears during mouse navigation on inventory and is also exaggerated if one has more than one monitor and the game is in windowed mode

**Comment by Tiagoquix** [comment]
Can confirm this happens to me as well.

**Comment by JustMoneko** [comment]
Is this patch still being worked on?

**Comment by kumfc** [comment]
> Is this patch still being worked on?

There's no release build for the latest version, but it fixes the issue. Build it yourself with Visual Studio.

**Comment by ermaccer** [comment]
Condensed code & updated release.
