### ISSUE TITLE
Not sure this works with the Steam version

### ISSUE THREAD

**Issue by RamouzK** [ermaccer/Worms4UHD.MouseFix#2]
Hi,

Thank you for this fix but I'm unable to make it work with Worms Ultimate Mayhem (latest Steam version). Is it for Worms Ultimate Mayhem or for Worms 4, the one from before 2011?

Thanks in advance!

**Comment by Bruh2801** [comment]
it is for ultimate mayhem. worms 4 (the old one ofc) probably doesnt have this issue.as far as i know atleast

**Comment by Tiagoquix** [comment]
Try using the Worms Ultimate Mayhem Anniversavy Patch together with this mod: https://github.com/heatray/WUMPatch

**Comment by RamouzK** [comment]
> Try using the Worms Ultimate Mayhem Anniversavy Patch together with this mod: https://github.com/heatray/WUMPatch

Thank you. It works.
